CREATE TABLE transaccion
(
    id_transaccion     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_cuenta_origen   BIGINT                      NOT NULL,
    id_cuenta_destino  BIGINT                      NOT NULL,
    tipo_transaccion   VARCHAR(15)                 NOT NULL,
    monto_transaccion  NUMERIC(19, 2)              NOT NULL,
    fecha_transaccion  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    descripcion        VARCHAR(35),
    estado             VARCHAR(15)                 NOT NULL,
    CONSTRAINT pk_transaccion PRIMARY KEY (id_transaccion),
    CONSTRAINT ck_transaccion_monto_positivo CHECK (monto_transaccion > 0),
    CONSTRAINT ck_transaccion_tipo CHECK (tipo_transaccion IN ('DEPOSITO', 'RETIRO', 'TRANSFERENCIA', 'PAGO')),
    CONSTRAINT ck_transaccion_estado CHECK (estado IN ('PENDIENTE', 'COMPLETADA', 'RECHAZADA', 'REVERTIDA'))
);

CREATE INDEX idx_transaccion_cuenta_origen ON transaccion (id_cuenta_origen);
CREATE INDEX idx_transaccion_cuenta_destino ON transaccion (id_cuenta_destino);
CREATE INDEX idx_transaccion_estado ON transaccion (estado);
CREATE INDEX idx_transaccion_tipo ON transaccion (tipo_transaccion);
CREATE INDEX idx_transaccion_fecha ON transaccion (fecha_transaccion);
