CREATE TABLE cliente
(
    rut_cliente      VARCHAR(12) NOT NULL,
    numero_serie     VARCHAR(9)  NOT NULL,
    nombre_cliente   VARCHAR(50) NOT NULL,
    apellido_cliente VARCHAR(50) NOT NULL,
    telefono_cliente VARCHAR(15) NOT NULL,
    email_cliente    VARCHAR(50),
    fecha_creacion   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    estado           SMALLINT    NOT NULL,
    id_profesion     BIGINT,
    CONSTRAINT pk_cliente PRIMARY KEY (rut_cliente)
);

CREATE TABLE direccion_cliente
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calle          VARCHAR(50)                             NOT NULL,
    numero         VARCHAR(5)                              NOT NULL,
    depta          VARCHAR(5)                              NOT NULL,
    tipo_direccion SMALLINT                                NOT NULL,
    ciudad         VARCHAR(50)                             NOT NULL,
    rut_cliente    VARCHAR(12),
    CONSTRAINT pk_direccioncliente PRIMARY KEY (id)
);

CREATE TABLE profesion
(
    id_profesion     BIGINT      NOT NULL,
    nombre_profesion VARCHAR(50) NOT NULL,
    CONSTRAINT pk_profesion PRIMARY KEY (id_profesion)
);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_numeroserie UNIQUE (numero_serie);

ALTER TABLE cliente
    ADD CONSTRAINT FK_CLIENTE_ON_ID_PROFESION FOREIGN KEY (id_profesion) REFERENCES profesion (id_profesion);

ALTER TABLE direccion_cliente
    ADD CONSTRAINT FK_DIRECCIONCLIENTE_ON_RUT_CLIENTE FOREIGN KEY (rut_cliente) REFERENCES cliente (rut_cliente);

INSERT INTO profesion (id_profesion, nombre_profesion) VALUES
(1, 'Ingeniero'),
(2, 'Doctor'),
(3, 'Abogado');

INSERT INTO cliente (rut_cliente, numero_serie, nombre_cliente, apellido_cliente, telefono_cliente, email_cliente, fecha_creacion, estado, id_profesion) VALUES
('11111111-1', '123456789', 'Juan', 'Perez', '+56911111111', 'juan.perez@mail.com', NOW(), 1, 1),
('22222222-2', '987654321', 'Maria', 'Gonzalez', '+56922222222', 'maria.gonzalez@mail.com', NOW(), 1, 2),
('33333333-3', '456123789', 'Pedro', 'Ramirez', '+56933333333', 'pedro.ramirez@mail.com', NOW(), 1, 3);

INSERT INTO direccion_cliente (calle, numero, depta, tipo_direccion, ciudad, rut_cliente) VALUES
('Av Siempre Viva', '742', '101', 1, 'Santiago', '11111111-1'),
('Los Carrera', '123', '202', 1, 'Valparaiso', '22222222-2'),
('O Higgins', '456', '303', 2, 'Concepcion', '33333333-3');
