CREATE TABLE usuario
(
    id_usuario     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(50)                 NOT NULL,
    password       VARCHAR(100)                NOT NULL,
    rol            VARCHAR(20)                 NOT NULL,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uc_usuario_username UNIQUE (username),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMIN', 'USER', 'OPERADOR'))
);

CREATE INDEX idx_usuario_username ON usuario (username);
CREATE INDEX idx_usuario_rol ON usuario (rol);
