CREATE TABLE sucursal
(
    id_sucursal     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre          VARCHAR(80)                 NOT NULL,
    email           VARCHAR(80)                 NOT NULL,
    telefono        VARCHAR(15)                 NOT NULL,
    estado          VARCHAR(15)                 NOT NULL,
    fecha_creacion  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal),
    CONSTRAINT uc_sucursal_nombre UNIQUE (nombre),
    CONSTRAINT uc_sucursal_email UNIQUE (email),
    CONSTRAINT ck_sucursal_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX idx_sucursal_estado ON sucursal (estado);
CREATE INDEX idx_sucursal_nombre ON sucursal (nombre);

CREATE TABLE ejecutivo
(
    id_ejecutivo   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre         VARCHAR(50) NOT NULL,
    apellido       VARCHAR(50) NOT NULL,
    email          VARCHAR(80) NOT NULL,
    telefono       VARCHAR(15) NOT NULL,
    cargo          VARCHAR(40) NOT NULL,
    estado         VARCHAR(15) NOT NULL,
    fecha_ingreso  DATE        NOT NULL,
    id_sucursal    BIGINT      NOT NULL,
    CONSTRAINT pk_ejecutivo PRIMARY KEY (id_ejecutivo),
    CONSTRAINT uc_ejecutivo_email UNIQUE (email),
    CONSTRAINT fk_ejecutivo_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal (id_sucursal),
    CONSTRAINT ck_ejecutivo_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX idx_ejecutivo_sucursal ON ejecutivo (id_sucursal);
CREATE INDEX idx_ejecutivo_estado ON ejecutivo (estado);
CREATE INDEX idx_ejecutivo_email ON ejecutivo (email);

CREATE TABLE direccion_sucursal
(
    id_direccion    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_direccion  VARCHAR(15) NOT NULL,
    calle           VARCHAR(80) NOT NULL,
    numero          VARCHAR(10) NOT NULL,
    depto           VARCHAR(10),
    ciudad          VARCHAR(50) NOT NULL,
    region          VARCHAR(50) NOT NULL,
    referencia      VARCHAR(100),
    id_sucursal     BIGINT      NOT NULL,
    CONSTRAINT pk_direccion_sucursal PRIMARY KEY (id_direccion),
    CONSTRAINT fk_direccion_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal (id_sucursal),
    CONSTRAINT ck_direccion_tipo CHECK (tipo_direccion IN ('MATRIZ', 'SUCURSAL', 'OFICINA', 'BODEGA'))
);

CREATE INDEX idx_direccion_sucursal ON direccion_sucursal (id_sucursal);
CREATE INDEX idx_direccion_ciudad ON direccion_sucursal (ciudad);
CREATE INDEX idx_direccion_tipo ON direccion_sucursal (tipo_direccion);

INSERT INTO sucursal (nombre, email, telefono, estado, fecha_creacion) VALUES
('NovaBank Casa Matriz', 'matriz@novabank.cl', '+56221110000', 'ACTIVO', NOW()),
('NovaBank Sucursal Centro', 'centro@novabank.cl', '+56221112233', 'ACTIVO', NOW()),
('NovaBank Sucursal Norte', 'norte@novabank.cl', '+56221114455', 'ACTIVO', NOW());

INSERT INTO ejecutivo (nombre, apellido, email, telefono, cargo, estado, fecha_ingreso, id_sucursal) VALUES
('Camila', 'Reyes', 'camila.reyes@novabank.cl', '+56911112222', 'Ejecutiva de Cuentas', 'ACTIVO', CURRENT_DATE, 1),
('Felipe', 'Soto', 'felipe.soto@novabank.cl', '+56933334444', 'Asesor Financiero', 'ACTIVO', CURRENT_DATE, 2);

INSERT INTO direccion_sucursal (tipo_direccion, calle, numero, depto, ciudad, region, referencia, id_sucursal) VALUES
('MATRIZ', 'Av Apoquindo', '4500', NULL, 'Santiago', 'Metropolitana', 'Frente al metro Manquehue', 1),
('SUCURSAL', 'Calle Estado', '200', NULL, 'Santiago', 'Metropolitana', 'Centro civico', 2),
('SUCURSAL', 'Av Tobalaba', '120', '5', 'Antofagasta', 'Antofagasta', NULL, 3);
