spring:
  datasource:
    url: jdbc:postgresql://34.16.103.65:5432/postgres
    username: panel-ciudadano-dev
    password: "F^TzfiihrKz^QHy`"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/